import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { getGithubPreviewProps, parseJson } from "next-tinacms-github";
import { GetStaticProps } from "next";
import { usePlugin, useCMS } from "tinacms";
import {
  useGithubJsonForm,
  useGithubMarkdownForm,
  useGithubToolbarPlugins,
} from "react-tinacms-github";

import ReactMarkdown from "react-markdown";
import { InlineWysiwyg } from "react-tinacms-editor";
import { InlineForm, InlineText } from "react-tinacms-inline";
import matter from "gray-matter";

export default function Home({ markdownFile }) {
  const cms = useCMS();
  const formOptions = {
    label: "Home Page",
    fields: [{ name: markdownFile.frontmatter.title }],
  };

  const [data2, form] = useGithubMarkdownForm(markdownFile, formOptions);
  usePlugin(form);
  useGithubToolbarPlugins();
  console.log(data2);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>
          {/* <InlineForm form={form}> */}
          {/* <InlineWysiwyg name="markdownBody" format="markdown"> */}
          <ReactMarkdown>{data2.markdownBody}</ReactMarkdown>
          {/* </InlineWysiwyg> */}
          {/* </InlineForm> */}
          <button onClick={() => cms.toggle()}>
            {cms.enabled ? "Exit Edit Mode" : "Edit This Site"}
          </button>
        </h1>
      </main>
    </div>
  );
}

/* export async function getStaticProps({ preview, previewData }) {
 *   if (preview) {
 *     return getGithubPreviewProps({
 *       ...previewData,
 *       fileRelativePath: "content/home.md",
 *       parse: parseJson,
 *     });
 *   }
 *   return {
 *     props: {
 *       sourceProvider: null,
 *       error: null,
 *       preview: false,
 *       file: {
 *         fileRelativePath: "content/home.md",
 *         data: (await import("../content/home.md")).default,
 *       },
 *     },
 *   };
 * } */
export async function getStaticProps() {
  /* const infoData = await import(`../content/home.md`); */
  /* const data = matter(infoData.default); */
  /* console.log(data); */

  return {
    props: {
      markdownFile: {
        frontmatter: { title: "[title placeholder]" },
        markdownBody: "[text]",
        fileRelativePath: `content/home.md`,
      },
    },
  };
}
